name: Keep API Alive

on:
  schedule:
    - cron: '*/25 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -f https://jogos-review-api.onrender.com/actuator/health \
          && echo "API está acordada ✅" \
          || echo "API não respondeu ⚠️"
